apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
 
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.spec.selector.app }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.spec.selector.app }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:

      containers:
        - name: {{ .Values.spec.containers.name }}
          image: "{{ .Values.spec.image.repository }}:{{ .Values.spec.image.tag }}"
          imagePullPolicy: {{ .Values.spec.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
         
