apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.spec.selector.app }}
  labels:
     run: {{ .Values.spec.selector.app }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.spec.selector.app }}
    app.kubernetes.io/instance: {{ .Release.Name }}
